# Generated by Django 3.2.4 on 2021-06-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_shared', '0001_initial'),
        ('sweet_tenant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SweetType',
            new_name='Sweet',
        ),
    ]
